---
# yamllint disable rule:line-length rule:truthy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      S3_BUCKET:
        required: true
        type: string
      S3_BUCKET_DEST:
        required: true
        type: string
      BINARY_NAME:
        required: false
        type: string
        default: "main"

env:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  YELLOW: '\033[1;33m'
  H_GREEN: '\033[97;42m'
  H_WHITE: '\033[90;47m'
  H_YELLOW: '\033[90;43m'
  H_RED: '\033[97;41m'
  H_BLUE: '\033[97;44m'
  H_MAGENTA: '\033[97;45m'
  H_CYAN: '\033[97;46m'
  NC: '\033[0m' # No Color
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  download-artifact-s3:
    name: Download artifact from S3
    runs-on: ubuntu-latest
    outputs:
      artifact-empty: ${{ steps.validate-artifact.outputs.artifact-empty }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifact from S3
        run: |

          VERSION=$(cat VERSION)
          REPO=$(basename $GITHUB_REPOSITORY)

          echo -e "${GREEN}Download from S3: ${YELLOW} ${{ inputs.S3_BUCKET }}${NC}"

          aws s3 cp s3://${{ inputs.S3_BUCKET }}/${REPO}/${VERSION}/ ./bin/ --recursive

      - name: Validate if artifact is empty
        id: validate-artifact
        run: |
          if [ -z "$(ls -A ./bin)" ]
          then
            echo "Empty"
            echo "artifact-empty=true" >>$GITHUB_OUTPUT
          else
            echo "Not Empty"
            echo "artifact-empty=false" >>$GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-code-artifact-s3
          path: bin/
          retention-days: 1

  zip-code:
    name: Zip code
    if: needs.download-artifact-s3.outputs.artifact-empty == 'false'
    runs-on: ubuntu-latest
    needs: download-artifact-s3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: go-code-artifact-s3
          path: bin/

      - name: Zip code
        run: |
          VERSION=$(cat VERSION)

          FILE_TYPE=$(file --brief * | head -n 1)
          REPO=$(basename $GITHUB_REPOSITORY)

          if [[ $FILE_TYPE == "directory" ]]
          then
            for module in $(ls ./bin)
            do
              echo -e "\nZIP_CODE: ${YELLOW}Zip file ./bin/${module}/${{ inputs.BINARY_NAME }}${NC}"
              
              cd ./bin/${module}
              zip "${VERSION}.zip" ${{ inputs.BINARY_NAME }}
              cd -

              mkdir -p ./zip/${module}
              mv "./bin/${module}/${VERSION}.zip" ./zip/${module}
              echo -e "ZIP_CODE: ${YELLOW}Versioned output: ./bin/${module}/${VERSION}.zip${NC}"
            done
          else
            echo -e "\nZIP_CODE: ${YELLOW}Zip file ./bin/${{ inputs.BINARY_NAME }}${NC}"
            
            cd ./bin 
            zip "${VERSION}.zip" ${{ inputs.BINARY_NAME }}
            cd -
            
            mkdir -p ./zip/${REPO}
            mv "./bin/${VERSION}.zip" ./zip/${REPO}/
            echo -e "ZIP_CODE: ${YELLOW}Versioned output: ./bin/${REPO}/${VERSION}.zip${NC}"
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-zip-artifact
          path: zip/
          retention-days: 1

  aws-push-code-to-lambda:
    name: Push code to Lambda
    runs-on: ubuntu-latest
    needs: zip-code
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: go-zip-artifact
          path: zip/

      - name: Push to S3
        run: |
          for module in $(ls -A ./zip); do
            echo -e "${GREEN}PUSH TO S3: ${YELLOW}Files in module ./zip/${module} will be pushed to lambda ${{ inputs.S3_BUCKET }}${NC}"
            aws s3 cp ./zip/${module} s3://${{ inputs.S3_BUCKET_DEST }}/${module} --recursive
          done

      - name: Deploy code to Lambda
        run: |
          if [ -d ./zip ] && [ "$(ls -A ./zip)" ]; then
            for module in $(ls -A ./zip); do
              package=$(ls ./zip/${module}/)

              echo -e "${GREEN}Deploy Lambda ${module}-${{ inputs.ENVIRONMENT }}${NC}: ${YELLOW}Package: ${package}${NC}"
              aws lambda update-function-code --function-name ${module}-${{ inputs.ENVIRONMENT }}  --s3-bucket ${{ inputs.S3_BUCKET_DEST }} --s3-key ${module}/${package} --publish
            done
          fi
